stages:
- name: compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn clean package -Dmaven.test.skip=true -U
    when:
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: web-demo
      registry: registry.cn-shenzhen.aliyuncs.com
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    event:
      include:
      - tag
timeout: 60
