stages:
- name: compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn clean package -Dmaven.test.skip=true -U
    when:
      event:
        include:
        - tag
  when:
    event:
      include:
      - tag
timeout: 60
